#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/user-api-base/ && \
    dotnet build src/user-api-base/ && \
    echo "Now, run the following to start the project: dotnet run -p src/user-api-base/user-api-base.csproj --launch-profile web"
